@extends('partials.app', ['title' => isset($purchase) ? 'Edit Purchase' : 'Create Purchase'])

@section('content')

    <div class="max-w-4xl mx-auto space-y-6 animate-fade-in">
        <div class="flex items-center justify-between">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div>
                <h1 class="text-2xl font-bold text-gray-900">
                    {{ isset($purchase) ? 'Edit Purchase' : 'Add New Purchase' }}
                </h1>
                <p class="text-sm text-gray-500 mt-1">Record incoming chicken meat stock purchases from your suppliers.</p>
            </div>
            <a href="{{ route('purchases.index') }}"
                class="btn-secondary flex items-center gap-2 text-sm bg-gray-100 hover:bg-gray-200 text-gray-700 px-4 py-2 rounded-lg transition-colors">
                <i class="fa-solid fa-arrow-left"></i> Back to List
            </a>
        </div>

        <div class="bg-white rounded-xl shadow-md border border-gray-100 overflow-hidden">
            <form id="purchaseForm" action="{{ route('purchases.store') }}" method="POST" class="p-6 sm:p-8 space-y-6">
                @csrf

                <input type="hidden" name="update_id" value="{{ old('update_id') ?? @$purchase->id }}">

                <div class="grid grid-cols-1 md:grid-cols-2 gap-6">

                    {{-- Voucher No (generated by backend) --}}
                    <div class="space-y-2 md:col-span-2">
                        <label for="voucher_no" class="block text-sm font-semibold text-gray-700">
                            Voucher No
                        </label>
                        <div class="relative">
                            <span class="absolute inset-y-0 left-0 flex items-center pl-3 text-gray-400">
                                <i class="fa-solid fa-hashtag"></i>
                            </span>
                            <input type="text" id="voucher_no" name="voucher_no" readonly
                                value="{{ old('voucher_no') ?? (@$purchase->voucher_no ?? ($voucher_no ?? '')) }}"
                                placeholder="Auto-generated"
                                class="w-full pl-10 pr-4 py-2.5 bg-gray-100 border border-gray-200 rounded-lg text-gray-700 font-semibold focus:outline-none cursor-not-allowed">
                        </div>
                        <p class="text-xs text-gray-400">Generated automatically by the system.</p>
                        @error('voucher_no')
                            <p class="text-red-500 text-xs font-medium mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    {{-- Product --}}
                    <div class="space-y-2">
                        <label for="product_id" class="block text-sm font-semibold text-gray-700">
                            Product <span class="text-red-500">*</span>
                        </label>
                        <div class="relative">
                            <span class="absolute inset-y-0 left-0 flex items-center pl-3 text-gray-400">
                                <i class="fa-solid fa-drumstick-bite"></i>
                            </span>
                            <select id="product_id" name="product_id" required
                                class="select2 w-full pl-10 pr-10 py-2.5 bg-gray-50 border @error('product_id') border-red-500 focus:ring-2 focus:ring-red-200 @else border-gray-200 focus:ring-2 focus:ring-amber-500 focus:border-amber-500 @enderror rounded-lg text-gray-900 focus:outline-none transition-colors appearance-none">

                                <option value="" disabled
                                    {{ old('product_id') === null && !isset($purchase) ? 'selected' : '' }}>
                                    Select a product
                                </option>

                                @foreach ($products as $product)
                                    <option value="{{ $product->id }}"
                                        {{ (string) old('product_id', @$purchase->product_id) === (string) $product->id ? 'selected' : '' }}>
                                        {{ $product->name }}
                                    </option>
                                @endforeach
                            </select>

                        </div>
                        @error('product_id')
                            <p class="text-red-500 text-xs font-medium mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    {{-- Supplier --}}
                    <div class="space-y-2">
                        <label for="supplier_id" class="block text-sm font-semibold text-gray-700">
                            Supplier <span class="text-red-500">*</span>
                        </label>
                        <div class="relative">
                            <span class="absolute inset-y-0 left-0 flex items-center pl-3 text-gray-400">
                                <i class="fa-solid fa-truck-field"></i>
                            </span>
                            <select id="supplier_id" name="supplier_id" required
                                class="select2 w-full pl-10 pr-10 py-2.5 bg-gray-50 border @error('supplier_id') border-red-500 focus:ring-2 focus:ring-red-200 @else border-gray-200 focus:ring-2 focus:ring-amber-500 focus:border-amber-500 @enderror rounded-lg text-gray-900 focus:outline-none transition-colors appearance-none">

                                <option value="" disabled
                                    {{ old('supplier_id') === null && !isset($purchase) ? 'selected' : '' }}>
                                    Select a supplier
                                </option>

                                @foreach ($suppliers as $supplier)
                                    <option value="{{ $supplier->id }}" data-region="{{ $supplier->region->name ?? '' }}"
                                        {{ (string) old('supplier_id', @$purchase->supplier_id) === (string) $supplier->id ? 'selected' : '' }}>
                                        {{ $supplier->name }}--{{ $supplier->region->name ?? '' }}
                                    </option>
                                @endforeach
                            </select>

                        </div>
                        <p id="regionHint" class="text-xs font-medium mt-1 hidden text-amber-600">
                            <i class="fa-solid fa-circle-info"></i> Punjab region supplier — an extra 2% of total weight
                            will be deducted as weight cut.
                        </p>
                        @error('supplier_id')
                            <p class="text-red-500 text-xs font-medium mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    {{-- Vehicles (Multiple) --}}
                    <div class="space-y-2 md:col-span-2">
                        <div class="flex items-center justify-between">
                            <label class="block text-sm font-semibold text-gray-700">
                                Vehicles <span class="text-red-500">*</span>
                            </label>
                            <button type="button" id="addVehicleBtn"
                                class="inline-flex items-center gap-1 text-xs font-medium text-amber-600 hover:text-amber-700 bg-amber-50 hover:bg-amber-100 px-3 py-1.5 rounded-lg transition-colors">
                                <i class="fa-solid fa-plus"></i> Add Vehicle
                            </button>
                        </div>

                        <div id="vehiclesContainer" class="space-y-3">
                            {{-- Vehicle entries will be generated here --}}
                        </div>

                        <p class="text-xs text-gray-400">Add one or more vehicle numbers for this purchase.</p>
                        @error('vehicles')
                            <p class="text-red-500 text-xs font-medium mt-1">{{ $message }}</p>
                        @enderror
                        @if ($errors->has('vehicles.*'))
                            @foreach ($errors->get('vehicles.*') as $messages)
                                @foreach ($messages as $message)
                                    <p class="text-red-500 text-xs font-medium mt-1">{{ $message }}</p>
                                @endforeach
                            @endforeach
                        @endif
                    </div>

                    {{-- Date --}}
                    <div class="space-y-2">
                        <label for="date" class="block text-sm font-semibold text-gray-700">
                            Date
                        </label>
                        <div class="relative">
                            <span
                                class="absolute inset-y-0 left-0 flex items-center pl-3 text-gray-400 font-medium text-sm">
                                <i class="fa-solid fa-calendar"></i>
                            </span>
                            <input type="date" id="date" name="date"
                                value="{{ old('date', isset($purchase) ? date('Y-m-d', strtotime($purchase->date)) : date('Y-m-d')) }}"
                                class="w-full pl-10 pr-4 py-2.5 bg-gray-50 border @error('date') border-red-500 focus:ring-2 focus:ring-red-200 @else border-gray-200 focus:ring-2 focus:ring-amber-500 focus:border-amber-500 @enderror rounded-lg text-gray-900 focus:outline-none transition-colors placeholder:text-gray-400">
                        </div>
                        @error('date')
                            <p class="text-red-500 text-xs font-medium mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    {{-- Crate Qty --}}
                    <div class="space-y-2">
                        <label for="crate_qty" class="block text-sm font-semibold text-gray-700">
                            Crate Quantity <span class="text-red-500">*</span>
                        </label>
                        <div class="relative">
                            <span class="absolute inset-y-0 left-0 flex items-center pl-3 text-gray-400">
                                <i class="fa-solid fa-boxes-stacked"></i>
                            </span>
                            <input type="number" step="1" min="0" id="crate_qty" name="crate_qty"
                                value="{{ old('crate_qty') ?? @$purchase->crate_qty }}" required placeholder="e.g., 20"
                                class="w-full pl-10 pr-4 py-2.5 bg-gray-50 border @error('crate_qty') border-red-500 focus:ring-2 focus:ring-red-200 @else border-gray-200 focus:ring-2 focus:ring-amber-500 focus:border-amber-500 @enderror rounded-lg text-gray-900 focus:outline-none transition-colors placeholder:text-gray-400">
                        </div>
                        <p class="text-xs text-gray-400">Each crate cuts 0.5 kg from the total weight automatically.</p>
                        @error('crate_qty')
                            <p class="text-red-500 text-xs font-medium mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    {{-- Total Weight --}}
                    <div class="space-y-2">
                        <label for="total_weight" class="block text-sm font-semibold text-gray-700">
                            Total Weight (kg) <span class="text-red-500">*</span>
                        </label>
                        <div class="relative">
                            <span class="absolute inset-y-0 left-0 flex items-center pl-3 text-gray-400">
                                <i class="fa-solid fa-weight-scale"></i>
                            </span>
                            <input type="number" step="0.01" min="0" id="total_weight" name="total_weight"
                                value="{{ old('total_weight') ?? @$purchase->total_weight }}" required placeholder="0.00"
                                class="w-full pl-10 pr-4 py-2.5 bg-gray-50 border @error('total_weight') border-red-500 focus:ring-2 focus:ring-red-200 @else border-gray-200 focus:ring-2 focus:ring-amber-500 focus:border-amber-500 @enderror rounded-lg text-gray-900 focus:outline-none transition-colors placeholder:text-gray-400">
                        </div>
                        @error('total_weight')
                            <p class="text-red-500 text-xs font-medium mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    {{-- Weight Cut (auto-calculated) --}}
                    <div class="space-y-2">
                        <label for="weight_cut" class="block text-sm font-semibold text-gray-700">
                            Weight Cut (kg)
                        </label>
                        <div class="relative">
                            <span class="absolute inset-y-0 left-0 flex items-center pl-3 text-gray-400">
                                <i class="fa-solid fa-scissors"></i>
                            </span>
                            <input type="number" step="0.01" min="0" id="weight_cut" name="weight_cut"
                                readonly value="{{ old('weight_cut') ?? (@$purchase->weight_cut ?? '0.00') }}"
                                placeholder="0.00"
                                class="w-full pl-10 pr-4 py-2.5 bg-gray-100 border border-gray-200 rounded-lg text-gray-700 focus:outline-none cursor-not-allowed">
                        </div>
                        <p class="text-xs text-gray-400">Auto-calculated: (crates × 0.5kg) + 2% of total weight if supplier
                            region is Punjab.</p>
                        @error('weight_cut')
                            <p class="text-red-500 text-xs font-medium mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    {{-- Net Weight (auto-calculated) --}}
                    <div class="space-y-2">
                        <label for="netweight" class="block text-sm font-semibold text-gray-700">
                            Net Weight (kg)
                        </label>
                        <div class="relative">
                            <span class="absolute inset-y-0 left-0 flex items-center pl-3 text-gray-400">
                                <i class="fa-solid fa-balance-scale"></i>
                            </span>
                            <input type="number" step="0.01" min="0" id="netweight" name="netweight"
                                readonly value="{{ old('netweight') ?? (@$purchase->netweight ?? '0.00') }}"
                                placeholder="0.00"
                                class="w-full pl-10 pr-4 py-2.5 bg-gray-100 border border-gray-200 rounded-lg text-gray-700 focus:outline-none cursor-not-allowed">
                        </div>
                        @error('netweight')
                            <p class="text-red-500 text-xs font-medium mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    {{-- Rate --}}
                    <div class="space-y-2">
                        <label for="rate" class="block text-sm font-semibold text-gray-700">
                            Rate (per kg) <span class="text-gray-400 font-normal">(optional)</span>
                        </label>
                        <div class="relative">
                            <span class="absolute inset-y-0 left-0 flex items-center pl-3 text-gray-400">
                                <i class="fa-solid fa-tag"></i>
                            </span>
                            <input type="number" step="0.01" min="0" id="rate" name="rate"
                                value="{{ old('rate') ?? @$purchase->rate }}" placeholder="To be decided later"
                                class="w-full pl-10 pr-4 py-2.5 bg-gray-50 border @error('rate') border-red-500 focus:ring-2 focus:ring-red-200 @else border-gray-200 focus:ring-2 focus:ring-amber-500 focus:border-amber-500 @enderror rounded-lg text-gray-900 focus:outline-none transition-colors placeholder:text-gray-400">
                        </div>
                        <p class="text-xs text-gray-400">Leave blank if the rate hasn't been decided yet — it will be saved
                            as empty and can be updated later.</p>
                        @error('rate')
                            <p class="text-red-500 text-xs font-medium mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    {{-- Total Amount (auto-calculated) --}}
                    <div class="space-y-2">
                        <label for="total_amount" class="block text-sm font-semibold text-gray-700">
                            Total Amount
                        </label>
                        <div class="relative">
                            <span
                                class="absolute inset-y-0 left-0 flex items-center pl-3 text-gray-400 font-medium text-sm">
                                <i class="fa-solid fa-wallet"></i>
                            </span>
                            <input type="number" step="0.01" min="0" id="total_amount" name="total_amount"
                                readonly value="{{ old('total_amount') ?? (@$purchase->total_amount ?? '0.00') }}"
                                placeholder="0.00"
                                class="w-full pl-10 pr-4 py-2.5 bg-gray-100 border border-gray-200 rounded-lg text-gray-700 font-semibold focus:outline-none cursor-not-allowed">
                        </div>
                        <p class="text-xs text-gray-400">Auto-calculated: Net Weight × Rate.</p>
                        @error('total_amount')
                            <p class="text-red-500 text-xs font-medium mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    {{-- Paid Amount --}}
                    <div class="space-y-2">
                        <label for="paid_amount" class="block text-sm font-semibold text-gray-700">
                            Paid Amount
                        </label>
                        <div class="relative">
                            <span class="absolute inset-y-0 left-0 flex items-center pl-3 text-gray-400">
                                <i class="fa-solid fa-money-bill-wave"></i>
                            </span>
                            <input type="number" step="0.01" min="0" id="paid_amount" name="paid_amount"
                                value="{{ old('paid_amount') ?? @$purchase->supplierPayment->amount }}"
                                placeholder="0.00"
                                class="w-full pl-10 pr-4 py-2.5 bg-gray-50 border @error('paid_amount') border-red-500 focus:ring-2 focus:ring-red-200 @else border-gray-200 focus:ring-2 focus:ring-amber-500 focus:border-amber-500 @enderror rounded-lg text-gray-900 focus:outline-none transition-colors placeholder:text-gray-400">
                        </div>
                        @error('paid_amount')
                            <p class="text-red-500 text-xs font-medium mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    {{-- Remaining Amount (auto-calculated) --}}
                    <div class="space-y-2">
                        <label for="remaining_amount" class="block text-sm font-semibold text-gray-700">
                            Remaining Balance
                        </label>
                        <div class="relative">
                            <span
                                class="absolute inset-y-0 left-0 flex items-center pl-3 text-gray-400 font-medium text-sm">
                                <i class="fa-solid fa-scale-unbalanced"></i>
                            </span>
                            <input type="number" step="0.01" min="0" id="remaining_amount"
                                name="remaining_amount" readonly
                                value="{{ old('remaining_amount') ?? (@$purchase->remaining_amount ?? '0.00') }}"
                                placeholder="0.00"
                                class="w-full pl-10 pr-4 py-2.5 bg-gray-100 border border-gray-200 rounded-lg text-gray-700 font-semibold focus:outline-none cursor-not-allowed">
                        </div>
                        <p class="text-xs text-gray-400">Auto-calculated: Total Amount - Paid Amount.</p>
                        @error('remaining_amount')
                            <p class="text-red-500 text-xs font-medium mt-1">{{ $message }}</p>
                            @enderror{{-- Vehicle Template (hidden) --}}
                            <template id="vehicleTemplate">
                                <div class="vehicle-entry flex gap-3 items-end">
                                    <div class="flex-1 space-y-1">
                                        <div class="relative">
                                            <span class="absolute inset-y-0 left-0 flex items-center pl-3 text-gray-400">
                                                <i class="fa-solid fa-truck"></i>
                                            </span>
                                            <input type="text" name="vehicles[INDEX][name]" placeholder="e.g., LEA-4521"
                                                class="vehicle-input w-full pl-10 pr-4 py-2.5 bg-gray-50 border border-gray-200 focus:ring-2 focus:ring-amber-500 focus:border-amber-500 rounded-lg text-gray-900 focus:outline-none transition-colors placeholder:text-gray-400"
                                                required>
                                        </div>
                                    </div>
                                    <button type="button"
                                        class="remove-vehicle-btn flex items-center justify-center w-10 h-10 rounded-lg bg-red-50 hover:bg-red-100 text-red-600 hover:text-red-700 transition-colors mb-0 flex-shrink-0"
                                        title="Remove this vehicle">
                                        <i class="fa-solid fa-trash-can text-sm"></i>
                                    </button>
                                </div>
                            </template>
                        </div>

                    </div>

                    <hr class="border-gray-100">

                    <div class="flex items-center justify-end gap-3 pt-2">
                        <button type="reset"
                            class="px-5 py-2.5 text-sm font-medium text-gray-600 hover:text-gray-800 transition-colors">
                            Reset Form
                        </button>
                        <button type="submit"
                            class="btn-primary inline-flex items-center gap-2 bg-amber-600 hover:bg-amber-700 text-white font-medium px-5 py-2.5 rounded-lg text-sm shadow-md hover:shadow-amber-500/20 transition-all">
                            <i class="fa-solid fa-cloud-arrow-up"></i> Save Purchase
                        </button>
                    </div>
                </form>
            </div>
        </div>

        {{-- Vehicle Template (hidden) --}}
        <template id="vehicleTemplate">
            <div class="vehicle-entry flex gap-3 items-end">
                <div class="flex-1 space-y-1">
                    <div class="relative">
                        <span class="absolute inset-y-0 left-0 flex items-center pl-3 text-gray-400">
                            <i class="fa-solid fa-truck"></i>
                        </span>
                        <input type="text" name="vehicles[INDEX][name]" placeholder="e.g., LEA-4521"
                            class="vehicle-input w-full pl-10 pr-4 py-2.5 bg-gray-50 border border-gray-200 focus:ring-2 focus:ring-amber-500 focus:border-amber-500 rounded-lg text-gray-900 focus:outline-none transition-colors placeholder:text-gray-400"
                            required>
                    </div>
                </div>
                <button type="button"
                    class="remove-vehicle-btn flex items-center justify-center w-10 h-10 rounded-lg bg-red-50 hover:bg-red-100 text-red-600 hover:text-red-700 transition-colors mb-0 flex-shrink-0"
                    title="Remove this vehicle">
                    <i class="fa-solid fa-trash-can text-sm"></i>
                </button>
            </div>
        </template>

        <script>
            $(document).ready(function() {
                $('.select2').select2();
            });

            // Vehicle Management
            (function() {
                const vehiclesContainer = document.getElementById('vehiclesContainer');
                const addVehicleBtn = document.getElementById('addVehicleBtn');
                const vehicleTemplate = document.getElementById('vehicleTemplate');
                let vehicleCount = 0;

                function createVehicleEntry(value = '') {
                    const clone = vehicleTemplate.content.cloneNode(true);
                    const input = clone.querySelector('.vehicle-input');
                    const removeBtn = clone.querySelector('.remove-vehicle-btn');

                    // Replace INDEX with actual count
                    input.name = `vehicles[${vehicleCount}][name]`;
                    vehicleCount++;

                    if (value) {
                        input.value = value;
                    }

                    removeBtn.addEventListener('click', function(e) {
                        e.preventDefault();
                        const entry = input.closest('.vehicle-entry');
                        if (vehiclesContainer.querySelectorAll('.vehicle-entry').length > 1) {
                            entry.remove();
                        } else {
                            alert('At least one vehicle is required.');
                        }
                    });

                    return clone;
                }

                function initializeVehicles() {
                    const rawVehicles = @json(old('vehicles')
                            ? old('vehicles')
                            : (isset($purchase) && $purchase->purchaseVehicles
                                ? $purchase->purchaseVehicles->pluck('name')->toArray()
                                : []));

                    // Normalize input data: extract string whether it's an object/array or direct string
                    const existingVehicles = rawVehicles.map(item => {
                        if (typeof item === 'object' && item !== null) {
                            return item.name || '';
                        }
                        return item;
                    });

                    if (existingVehicles.length > 0) {
                        existingVehicles.forEach(vehicleName => {
                            vehiclesContainer.appendChild(createVehicleEntry(vehicleName));
                        });
                    } else {
                        vehiclesContainer.appendChild(createVehicleEntry());
                    }
                }

                addVehicleBtn.addEventListener('click', function(e) {
                    e.preventDefault();
                    vehiclesContainer.appendChild(createVehicleEntry());
                });

                // Initialize on page load
                initializeVehicles();
            })();

            // Calculation Logic
            (function() {
                const cratesInput = document.getElementById('crate_qty');
                const totalWeightInput = document.getElementById('total_weight');
                const weightCutInput = document.getElementById('weight_cut');
                const netWeightInput = document.getElementById('netweight');
                const rateInput = document.getElementById('rate');
                const totalAmountInput = document.getElementById('total_amount');
                const paidAmountInput = document.getElementById('paid_amount');
                const remainingAmountInput = document.getElementById('remaining_amount');
                const supplierSelect = document.getElementById('supplier_id');
                const regionHint = document.getElementById('regionHint');

                const CRATE_CUT_PER_UNIT = 0.5; // kg cut per crate
                const PUNJAB_CUT_PERCENT = 0.02; // 2% of total weight for Punjab suppliers

                function isPunjabSupplier() {
                    const selectedOption = supplierSelect.options[supplierSelect.selectedIndex];
                    const region = selectedOption ? (selectedOption.getAttribute('data-region') || '') : '';
                    return region.trim().toLowerCase() === 'punjab';
                }

                function recalculate() {
                    const crateQty = parseFloat(cratesInput.value) || 0;
                    const totalWeight = parseFloat(totalWeightInput.value) || 0;
                    const rate = parseFloat(rateInput.value) || 0;
                    const paidAmount = parseFloat(paidAmountInput.value) || 0;

                    const crateCut = crateQty * CRATE_CUT_PER_UNIT;
                    const punjab = isPunjabSupplier();
                    const regionCut = punjab ? (totalWeight * PUNJAB_CUT_PERCENT) : 0;

                    regionHint.classList.toggle('hidden', !punjab);

                    let weightCut = crateCut + regionCut;
                    let netWeight = totalWeight - weightCut;
                    if (netWeight < 0) netWeight = 0;

                    const totalAmount = netWeight * rate;
                    let remainingAmount = totalAmount - paidAmount;
                    if (remainingAmount < 0) remainingAmount = 0;

                    weightCutInput.value = weightCut.toFixed(2);
                    netWeightInput.value = netWeight.toFixed(2);
                    totalAmountInput.value = totalAmount.toFixed(2);
                    remainingAmountInput.value = remainingAmount.toFixed(2);
                }

                [cratesInput, totalWeightInput, rateInput, paidAmountInput].forEach(el => {
                    el.addEventListener('input', recalculate);
                });
                supplierSelect.addEventListener('change', recalculate);

                // Run once on load (handles edit mode / old() repopulation)
                recalculate();
            })();
        </script>
    @endsection
