@extends('partials.app', ['title' => isset($sale) ? 'Edit Hotel Sale' : 'Create Hotel Sale'])

@section('content')
    <div class="max-w-4xl mx-auto space-y-6 animate-fade-in">
        <div class="flex items-center justify-between">
            <div>
                <h1 class="text-2xl font-bold text-gray-900">
                    {{ isset($sale) ? 'Edit Hotel Sale' : 'Add New Hotel Sale' }}
                </h1>
                <p class="text-sm text-gray-500 mt-1">Record direct weight-based sales for hotels and restaurants.</p>
            </div>
            <a href="{{ route('sales.index') }}"
                class="btn-secondary flex items-center gap-2 text-sm bg-gray-100 hover:bg-gray-200 text-gray-700 px-4 py-2 rounded-lg transition-colors">
                <i class="fa-solid fa-arrow-left"></i> Back to List
            </a>
        </div>

        <div class="bg-white rounded-xl shadow-md border border-gray-100 overflow-hidden">
            <form id="hotelSaleForm" action="{{ route('hotel_sales.store') }}" method="POST" class="p-6 sm:p-8 space-y-6">
                @csrf

                <input type="hidden" name="update_id" value="{{ old('update_id') ?? @$sale->id }}">

                <div class="grid grid-cols-1 md:grid-cols-2 gap-6">

                    {{-- Voucher No (generated by backend) --}}
                    <div class="space-y-2 md:col-span-2">
                        <label for="voucher_no" class="block text-sm font-semibold text-gray-700">
                            Voucher No
                        </label>
                        <div class="relative">
                            <span class="absolute inset-y-0 left-0 flex items-center pl-3 text-gray-400">
                                <i class="fa-solid fa-hashtag"></i>
                            </span>
                            <input type="text" id="voucher_no" name="voucher_no" readonly
                                value="{{ old('voucher_no') ?? (@$sale->voucher_no ?? ($voucher_no ?? '')) }}"
                                placeholder="Auto-generated"
                                class="w-full pl-10 pr-4 py-2.5 bg-gray-100 border border-gray-200 rounded-lg text-gray-700 font-semibold focus:outline-none cursor-not-allowed">
                        </div>
                        <p class="text-xs text-gray-400">Generated automatically by the system.</p>
                        @error('voucher_no')
                            <p class="text-red-500 text-xs font-medium mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    {{-- Product --}}
                    <div class="space-y-2">
                        <label for="product_id" class="block text-sm font-semibold text-gray-700">
                            Product <span class="text-red-500">*</span>
                        </label>
                        <div class="relative">
                            <span class="absolute inset-y-0 left-0 flex items-center pl-3 text-gray-400">
                                <i class="fa-solid fa-drumstick-bite"></i>
                            </span>
                            <select id="product_id" name="product_id" required
                                class="select2 w-full pl-10 pr-10 py-2.5 bg-gray-50 border @error('product_id') border-red-500 focus:ring-2 focus:ring-red-200 @else border-gray-200 focus:ring-2 focus:ring-amber-500 focus:border-amber-500 @enderror rounded-lg text-gray-900 focus:outline-none transition-colors appearance-none">

                                <option value="" disabled
                                    {{ old('product_id') === null && !isset($sale) ? 'selected' : '' }}>
                                    Select a product
                                </option>

                                @foreach ($products as $product)
                                    <option value="{{ $product->id }}"
                                        {{ (string) old('product_id', @$sale->product_id) === (string) $product->id ? 'selected' : '' }}>
                                        {{ $product->name }}
                                    </option>
                                @endforeach
                            </select>

                        </div>
                        @error('product_id')
                            <p class="text-red-500 text-xs font-medium mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    {{-- Customer (Hotel/Restaurant) --}}
                    <div class="space-y-2">
                        <label for="customer_id" class="block text-sm font-semibold text-gray-700">
                            Customer / Hotel <span class="text-red-500">*</span>
                        </label>
                        <div class="relative">
                            <span class="absolute inset-y-0 left-0 flex items-center pl-3 text-gray-400">
                                <i class="fa-solid fa-hotel"></i>
                            </span>
                            <select id="customer_id" name="customer_id" required
                                class="select2 w-full pl-10 pr-10 py-2.5 bg-gray-50 border @error('customer_id') border-red-500 focus:ring-2 focus:ring-red-200 @else border-gray-200 focus:ring-2 focus:ring-amber-500 focus:border-amber-500 @enderror rounded-lg text-gray-900 focus:outline-none transition-colors appearance-none">

                                <option value="" disabled
                                    {{ old('customer_id') === null && !isset($sale) ? 'selected' : '' }}>
                                    Select a hotel customer
                                </option>

                                @foreach ($customers as $customer)
                                    <option value="{{ $customer->id }}"
                                        {{ (string) old('customer_id', @$sale->customer_id) === (string) $customer->id ? 'selected' : '' }}>
                                        {{ $customer->name }} -- {{ $customer->region->name ?? 'N/A' }}
                                    </option>
                                @endforeach
                            </select>

                        </div>
                        @error('customer_id')
                            <p class="text-red-500 text-xs font-medium mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    {{-- Date --}}
                    <div class="space-y-2">
                        <label for="date" class="block text-sm font-semibold text-gray-700">
                            Date <span class="text-red-500">*</span>
                        </label>
                        <div class="relative">
                            <span class="absolute inset-y-0 left-0 flex items-center pl-3 text-gray-400">
                                <i class="fa-solid fa-calendar"></i>
                            </span>
                            <input type="date" id="date" name="date"
                                value="{{ old('date', isset($sale) ? date('Y-m-d', strtotime($sale->date)) : date('Y-m-d')) }}"
                                class="w-full pl-10 pr-4 py-2.5 bg-gray-50 border @error('date') border-red-500 focus:ring-2 focus:ring-red-200 @else border-gray-200 focus:ring-2 focus:ring-amber-500 focus:border-amber-500 @enderror rounded-lg text-gray-900 focus:outline-none transition-colors">
                        </div>
                        @error('date')
                            <p class="text-red-500 text-xs font-medium mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    {{-- Total Weight --}}
                    <div class="space-y-2">
                        <label for="total_weight" class="block text-sm font-semibold text-gray-700">
                            Total Weight (kg) <span class="text-red-500">*</span>
                        </label>
                        <div class="relative">
                            <span class="absolute inset-y-0 left-0 flex items-center pl-3 text-gray-400">
                                <i class="fa-solid fa-weight-scale"></i>
                            </span>
                            <input type="number" step="0.01" min="0" id="total_weight" name="total_weight"
                                value="{{ old('total_weight') ?? @$sale->total_weight }}" required placeholder="0.00"
                                class="w-full pl-10 pr-4 py-2.5 bg-gray-50 border @error('total_weight') border-red-500 focus:ring-2 focus:ring-red-200 @else border-gray-200 focus:ring-2 focus:ring-amber-500 focus:border-amber-500 @enderror rounded-lg text-gray-900 focus:outline-none transition-colors placeholder:text-gray-400">
                        </div>
                        @error('total_weight')
                            <p class="text-red-500 text-xs font-medium mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    {{-- Rate (per kg) --}}
                    <div class="space-y-2">
                        <label for="rate" class="block text-sm font-semibold text-gray-700">
                            Rate (per kg) <span class="text-red-500">*</span>
                        </label>
                        <div class="relative">
                            <span class="absolute inset-y-0 left-0 flex items-center pl-3 text-gray-400">
                                <i class="fa-solid fa-tag"></i>
                            </span>
                            <input type="number" step="0.01" min="0" id="rate" name="rate" required
                                value="{{ old('rate') ?? @$sale->rate }}" placeholder="0.00"
                                class="w-full pl-10 pr-4 py-2.5 bg-gray-50 border @error('rate') border-red-500 focus:ring-2 focus:ring-red-200 @else border-gray-200 focus:ring-2 focus:ring-amber-500 focus:border-amber-500 @enderror rounded-lg text-gray-900 focus:outline-none transition-colors placeholder:text-gray-400">
                        </div>
                        @error('rate')
                            <p class="text-red-500 text-xs font-medium mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    {{-- Total Amount (auto-calculated: Total Weight × Rate) --}}
                    <div class="space-y-2">
                        <label for="total_amount" class="block text-sm font-semibold text-gray-700">
                            Total Amount
                        </label>
                        <div class="relative">
                            <span class="absolute inset-y-0 left-0 flex items-center pl-3 text-gray-400">
                                <i class="fa-solid fa-wallet"></i>
                            </span>
                            <input type="number" step="0.01" min="0" id="total_amount" name="total_amount"
                                readonly value="{{ old('total_amount') ?? (@$sale->total_amount ?? '0.00') }}"
                                placeholder="0.00"
                                class="w-full pl-10 pr-4 py-2.5 bg-gray-100 border border-gray-200 rounded-lg text-gray-700 font-semibold focus:outline-none cursor-not-allowed">
                        </div>
                        <p class="text-xs text-gray-400">Calculated: Total Weight × Rate</p>
                        @error('total_amount')
                            <p class="text-red-500 text-xs font-medium mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    {{-- Amount Received --}}
                    <div class="space-y-2">
                        <label for="amount_received" class="block text-sm font-semibold text-gray-700">
                            Amount Received
                        </label>
                        <div class="relative">
                            <span class="absolute inset-y-0 left-0 flex items-center pl-3 text-gray-400">
                                <i class="fa-solid fa-hand-holding-dollar"></i>
                            </span>
                            <input type="number" step="0.01" min="0" id="amount_received"
                                name="amount_received"
                                value="{{ old('amount_received') ?? (@$sale->customerPayment->amount ?? '0.00') }}"
                                placeholder="0.00"
                                class="w-full pl-10 pr-4 py-2.5 bg-gray-50 border @error('amount_received') border-red-500 focus:ring-2 focus:ring-red-200 @else border-gray-200 focus:ring-2 focus:ring-amber-500 focus:border-amber-500 @enderror rounded-lg text-gray-900 focus:outline-none transition-colors placeholder:text-gray-400">
                        </div>
                        <p class="text-xs text-gray-400">Enter cash or partial payment collected upfront.</p>
                        @error('amount_received')
                            <p class="text-red-500 text-xs font-medium mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    {{-- Remaining Balance Indicator --}}
                    <div class="space-y-2 md:col-span-2">
                        <label for="due_amount" class="block text-sm font-semibold text-gray-700">
                            Remaining Balance / Due Amount
                        </label>
                        <div class="relative">
                            <span class="absolute inset-y-0 left-0 flex items-center pl-3 text-gray-400">
                                <i class="fa-solid fa-scale-unbalanced"></i>
                            </span>
                            <input type="number" step="0.01" id="due_amount" readonly value="0.00"
                                placeholder="0.00"
                                class="w-full pl-10 pr-4 py-2.5 bg-gray-100 border border-gray-200 rounded-lg text-gray-700 font-semibold focus:outline-none cursor-not-allowed">
                        </div>
                        <p class="text-xs text-gray-400">Calculated: Total Amount − Amount Received</p>
                    </div>

                </div>

                <hr class="border-gray-100">

                <div class="flex items-center justify-end gap-3 pt-2">
                    <button type="reset"
                        class="px-5 py-2.5 text-sm font-medium text-gray-600 hover:text-gray-800 transition-colors">
                        Reset Form
                    </button>
                    <button type="submit"
                        class="btn-primary inline-flex items-center gap-2 bg-amber-600 hover:bg-amber-700 text-white font-medium px-5 py-2.5 rounded-lg text-sm shadow-md hover:shadow-amber-500/20 transition-all">
                        <i class="fa-solid fa-cloud-arrow-up"></i> Save Sale
                    </button>
                </div>
            </form>
        </div>
    </div>

    <script>
        $(document).ready(function() {
            $('.select2').select2();
        });
        (function() {
            const totalWeightInput = document.getElementById('total_weight');
            const rateInput = document.getElementById('rate');
            const totalAmountInput = document.getElementById('total_amount');
            const amountReceivedInput = document.getElementById('amount_received');
            const dueAmountInput = document.getElementById('due_amount');

            function recalculate() {
                const totalWeight = parseFloat(totalWeightInput.value) || 0;
                const rate = parseFloat(rateInput.value) || 0;
                const amountReceived = parseFloat(amountReceivedInput.value) || 0;

                // Total Amount = Total Weight * Rate
                const totalAmount = totalWeight * rate;
                totalAmountInput.value = totalAmount.toFixed(2);

                // Due Amount = Total Amount - Amount Received
                const dueAmount = totalAmount - amountReceived;
                dueAmountInput.value = dueAmount.toFixed(2);
            }

            [totalWeightInput, rateInput, amountReceivedInput].forEach(el => {
                el.addEventListener('input', recalculate);
            });

            // Initial calculation on page load
            recalculate();
        })();
    </script>
@endsection
