@extends('partials.app', ['title' => isset($purchase) ? 'Edit Purchase' : 'Create Purchase'])

@section('content')
    <div class="max-w-4xl mx-auto space-y-6 animate-fade-in">
        <div class="flex items-center justify-between">
            <div>
                <h1 class="text-2xl font-bold text-gray-900">
                    {{ isset($purchase) ? 'Edit Purchase' : 'Add New Purchase' }}
                </h1>
                <p class="text-sm text-gray-500 mt-1">Record incoming chicken meat stock purchases from your suppliers.</p>
            </div>
            <a href="{{ route('purchases.index') }}"
                class="btn-secondary flex items-center gap-2 text-sm bg-gray-100 hover:bg-gray-200 text-gray-700 px-4 py-2 rounded-lg transition-colors">
                <i class="fa-solid fa-arrow-left"></i> Back to List
            </a>
        </div>

        <div class="bg-white rounded-xl shadow-md border border-gray-100 overflow-hidden">
            <form id="purchaseForm" action="{{ route('purchases.store') }}" method="POST" class="p-6 sm:p-8 space-y-6">
                @csrf

                <input type="hidden" name="update_id" value="{{ old('update_id') ?? @$purchase->id }}">

                <div class="grid grid-cols-1 md:grid-cols-2 gap-6">

                    {{-- Voucher No (generated by backend) --}}
                    <div class="space-y-2 md:col-span-2">
                        <label for="voucher_no" class="block text-sm font-semibold text-gray-700">
                            Voucher No
                        </label>
                        <div class="relative">
                            <span class="absolute inset-y-0 left-0 flex items-center pl-3 text-gray-400">
                                <i class="fa-solid fa-hashtag"></i>
                            </span>
                            <input type="text" id="voucher_no" name="voucher_no" readonly
                                value="{{ old('voucher_no') ?? @$purchase->voucher_no ?? $voucher_no ?? '' }}"
                                placeholder="Auto-generated"
                                class="w-full pl-10 pr-4 py-2.5 bg-gray-100 border border-gray-200 rounded-lg text-gray-700 font-semibold focus:outline-none cursor-not-allowed">
                        </div>
                        <p class="text-xs text-gray-400">Generated automatically by the system.</p>
                        @error('voucher_no')
                            <p class="text-red-500 text-xs font-medium mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    {{-- Product --}}
                    <div class="space-y-2">
                        <label for="product_id" class="block text-sm font-semibold text-gray-700">
                            Product <span class="text-red-500">*</span>
                        </label>
                        <div class="relative">
                            <span class="absolute inset-y-0 left-0 flex items-center pl-3 text-gray-400">
                                <i class="fa-solid fa-drumstick-bite"></i>
                            </span>
                            <select id="product_id" name="product_id" required
                                class="w-full pl-10 pr-10 py-2.5 bg-gray-50 border @error('product_id') border-red-500 focus:ring-2 focus:ring-red-200 @else border-gray-200 focus:ring-2 focus:ring-amber-500 focus:border-amber-500 @enderror rounded-lg text-gray-900 focus:outline-none transition-colors appearance-none">

                                <option value="" disabled {{ old('product_id') === null && !isset($purchase) ? 'selected' : '' }}>
                                    Select a product
                                </option>

                                @foreach ($products as $product)
                                    <option value="{{ $product->id }}"
                                        {{ (string) old('product_id', @$purchase->product_id) === (string) $product->id ? 'selected' : '' }}>
                                        {{ $product->name }}
                                    </option>
                                @endforeach
                            </select>
                            <span class="absolute inset-y-0 right-0 flex items-center pr-3 pointer-events-none text-gray-400">
                                <i class="fa-solid fa-chevron-down text-xs"></i>
                            </span>
                        </div>
                        @error('product_id')
                            <p class="text-red-500 text-xs font-medium mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    {{-- Supplier --}}
                    <div class="space-y-2">
                        <label for="supplier_id" class="block text-sm font-semibold text-gray-700">
                            Supplier <span class="text-red-500">*</span>
                        </label>
                        <div class="relative">
                            <span class="absolute inset-y-0 left-0 flex items-center pl-3 text-gray-400">
                                <i class="fa-solid fa-truck-field"></i>
                            </span>
                            <select id="supplier_id" name="supplier_id" required
                                class="w-full pl-10 pr-10 py-2.5 bg-gray-50 border @error('supplier_id') border-red-500 focus:ring-2 focus:ring-red-200 @else border-gray-200 focus:ring-2 focus:ring-amber-500 focus:border-amber-500 @enderror rounded-lg text-gray-900 focus:outline-none transition-colors appearance-none">

                                <option value="" disabled {{ old('supplier_id') === null && !isset($purchase) ? 'selected' : '' }}>
                                    Select a supplier
                                </option>

                                @foreach ($suppliers as $supplier)
                                    <option value="{{ $supplier->id }}"
                                        data-region="{{ $supplier->region->name ?? '' }}"
                                        {{ (string) old('supplier_id', @$purchase->supplier_id) === (string) $supplier->id ? 'selected' : '' }}>
                                        {{ $supplier->name }}--{{$supplier->region->name  }}
                                    </option>
                                @endforeach
                            </select>
                            <span class="absolute inset-y-0 right-0 flex items-center pr-3 pointer-events-none text-gray-400">
                                <i class="fa-solid fa-chevron-down text-xs"></i>
                            </span>
                        </div>
                        <p id="regionHint" class="text-xs font-medium mt-1 hidden text-amber-600">
                            <i class="fa-solid fa-circle-info"></i> Punjab region supplier — an extra 2% of total weight will be deducted as weight cut.
                        </p>
                        @error('supplier_id')
                            <p class="text-red-500 text-xs font-medium mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    {{-- Vehicle No --}}
                    <div class="space-y-2">
                        <label for="vehicle_no" class="block text-sm font-semibold text-gray-700">
                            Vehicle No <span class="text-red-500">*</span>
                        </label>
                        <div class="relative">
                            <span class="absolute inset-y-0 left-0 flex items-center pl-3 text-gray-400">
                                <i class="fa-solid fa-truck"></i>
                            </span>
                            <input type="text" id="vehicle_no" name="vehicle_no"
                                value="{{ old('vehicle_no') ?? @$purchase->vehicle_no }}" required
                                placeholder="e.g., LEA-4521"
                                class="w-full pl-10 pr-4 py-2.5 bg-gray-50 border @error('vehicle_no') border-red-500 focus:ring-2 focus:ring-red-200 @else border-gray-200 focus:ring-2 focus:ring-amber-500 focus:border-amber-500 @enderror rounded-lg text-gray-900 focus:outline-none transition-colors placeholder:text-gray-400">
                        </div>
                        @error('vehicle_no')
                            <p class="text-red-500 text-xs font-medium mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    {{-- Rate Date --}}
                    <div class="space-y-2">
                        <label for="date" class="block text-sm font-semibold text-gray-700">
                            Date
                        </label>
                        <div class="relative">
                            <span class="absolute inset-y-0 left-0 flex items-center pl-3 text-gray-400 font-medium text-sm">
                                <i class="fa-solid fa-calendar"></i>
                            </span>
                            <input type="date" id="date" name="date"
                                value="{{ old('date', isset($purchase) ? date('Y-m-d', strtotime($purchase->date)) : date('Y-m-d')) }}"
                                class="w-full pl-10 pr-4 py-2.5 bg-gray-50 border @error('date') border-red-500 focus:ring-2 focus:ring-red-200 @else border-gray-200 focus:ring-2 focus:ring-amber-500 focus:border-amber-500 @enderror rounded-lg text-gray-900 focus:outline-none transition-colors placeholder:text-gray-400">
                        </div>
                        @error('date')
                            <p class="text-red-500 text-xs font-medium mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    {{-- Crate Qty --}}
                    <div class="space-y-2">
                        <label for="crate_qty" class="block text-sm font-semibold text-gray-700">
                            Crate Quantity <span class="text-red-500">*</span>
                        </label>
                        <div class="relative">
                            <span class="absolute inset-y-0 left-0 flex items-center pl-3 text-gray-400">
                                <i class="fa-solid fa-boxes-stacked"></i>
                            </span>
                            <input type="number" step="1" min="0" id="crate_qty" name="crate_qty"
                                value="{{ old('crate_qty') ?? @$purchase->crate_qty }}" required
                                placeholder="e.g., 20"
                                class="w-full pl-10 pr-4 py-2.5 bg-gray-50 border @error('crate_qty') border-red-500 focus:ring-2 focus:ring-red-200 @else border-gray-200 focus:ring-2 focus:ring-amber-500 focus:border-amber-500 @enderror rounded-lg text-gray-900 focus:outline-none transition-colors placeholder:text-gray-400">
                        </div>
                        <p class="text-xs text-gray-400">Each crate cuts 0.5 kg from the total weight automatically.</p>
                        @error('crate_qty')
                            <p class="text-red-500 text-xs font-medium mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    {{-- Total Weight --}}
                    <div class="space-y-2">
                        <label for="total_weight" class="block text-sm font-semibold text-gray-700">
                            Total Weight (kg) <span class="text-red-500">*</span>
                        </label>
                        <div class="relative">
                            <span class="absolute inset-y-0 left-0 flex items-center pl-3 text-gray-400">
                                <i class="fa-solid fa-weight-scale"></i>
                            </span>
                            <input type="number" step="0.01" min="0" id="total_weight" name="total_weight"
                                value="{{ old('total_weight') ?? @$purchase->total_weight }}" required
                                placeholder="0.00"
                                class="w-full pl-10 pr-4 py-2.5 bg-gray-50 border @error('total_weight') border-red-500 focus:ring-2 focus:ring-red-200 @else border-gray-200 focus:ring-2 focus:ring-amber-500 focus:border-amber-500 @enderror rounded-lg text-gray-900 focus:outline-none transition-colors placeholder:text-gray-400">
                        </div>
                        @error('total_weight')
                            <p class="text-red-500 text-xs font-medium mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    {{-- Weight Cut (auto-calculated, still editable overrides allowed) --}}
                    <div class="space-y-2">
                        <label for="weight_cut" class="block text-sm font-semibold text-gray-700">
                            Weight Cut (kg)
                        </label>
                        <div class="relative">
                            <span class="absolute inset-y-0 left-0 flex items-center pl-3 text-gray-400">
                                <i class="fa-solid fa-scissors"></i>
                            </span>
                            <input type="number" step="0.01" min="0" id="weight_cut" name="weight_cut" readonly
                                value="{{ old('weight_cut') ?? @$purchase->weight_cut ?? '0.00' }}"
                                placeholder="0.00"
                                class="w-full pl-10 pr-4 py-2.5 bg-gray-100 border border-gray-200 rounded-lg text-gray-700 focus:outline-none cursor-not-allowed">
                        </div>
                        <p class="text-xs text-gray-400">Auto-calculated: (crates × 0.5kg) + 2% of total weight if supplier region is Punjab.</p>
                        @error('weight_cut')
                            <p class="text-red-500 text-xs font-medium mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    {{-- Net Weight (auto-calculated) --}}
                    <div class="space-y-2">
                        <label for="netweight" class="block text-sm font-semibold text-gray-700">
                            Net Weight (kg)
                        </label>
                        <div class="relative">
                            <span class="absolute inset-y-0 left-0 flex items-center pl-3 text-gray-400">
                                <i class="fa-solid fa-balance-scale"></i>
                            </span>
                            <input type="number" step="0.01" min="0" id="netweight" name="netweight" readonly
                                value="{{ old('netweight') ?? @$purchase->netweight ?? '0.00' }}"
                                placeholder="0.00"
                                class="w-full pl-10 pr-4 py-2.5 bg-gray-100 border border-gray-200 rounded-lg text-gray-700 focus:outline-none cursor-not-allowed">
                        </div>
                        @error('netweight')
                            <p class="text-red-500 text-xs font-medium mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    {{-- Rate (optional — may be decided later) --}}
                    <div class="space-y-2">
                        <label for="rate" class="block text-sm font-semibold text-gray-700">
                            Rate (per kg) <span class="text-gray-400 font-normal">(optional)</span>
                        </label>
                        <div class="relative">
                            <span class="absolute inset-y-0 left-0 flex items-center pl-3 text-gray-400">
                                <i class="fa-solid fa-tag"></i>
                            </span>
                            <input type="number" step="0.01" min="0" id="rate" name="rate"
                                value="{{ old('rate') ?? @$purchase->rate }}"
                                placeholder="To be decided later"
                                class="w-full pl-10 pr-4 py-2.5 bg-gray-50 border @error('rate') border-red-500 focus:ring-2 focus:ring-red-200 @else border-gray-200 focus:ring-2 focus:ring-amber-500 focus:border-amber-500 @enderror rounded-lg text-gray-900 focus:outline-none transition-colors placeholder:text-gray-400">
                        </div>
                        <p class="text-xs text-gray-400">Leave blank if the rate hasn't been decided yet — it will be saved as empty and can be updated later.</p>
                        @error('rate')
                            <p class="text-red-500 text-xs font-medium mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    {{-- Total Amount (auto-calculated) --}}
                    <div class="space-y-2 md:col-span-2">
                        <label for="total_amount" class="block text-sm font-semibold text-gray-700">
                            Total Amount
                        </label>
                        <div class="relative">
                            <span class="absolute inset-y-0 left-0 flex items-center pl-3 text-gray-400 font-medium text-sm">
                                <i class="fa-solid fa-wallet"></i>
                            </span>
                            <input type="number" step="0.01" min="0" id="total_amount" name="total_amount" readonly
                                value="{{ old('total_amount') ?? @$purchase->total_amount ?? '0.00' }}"
                                placeholder="0.00"
                                class="w-full pl-10 pr-4 py-2.5 bg-gray-100 border border-gray-200 rounded-lg text-gray-700 font-semibold focus:outline-none cursor-not-allowed">
                        </div>
                        <p class="text-xs text-gray-400">Auto-calculated: Net Weight × Rate.</p>
                        @error('total_amount')
                            <p class="text-red-500 text-xs font-medium mt-1">{{ $message }}</p>
                        @enderror
                    </div>
                </div>

                <hr class="border-gray-100">

                <div class="flex items-center justify-end gap-3 pt-2">
                    <button type="reset"
                        class="px-5 py-2.5 text-sm font-medium text-gray-600 hover:text-gray-800 transition-colors">
                        Reset Form
                    </button>
                    <button type="submit"
                        class="btn-primary inline-flex items-center gap-2 bg-amber-600 hover:bg-amber-700 text-white font-medium px-5 py-2.5 rounded-lg text-sm shadow-md hover:shadow-amber-500/20 transition-all">
                        <i class="fa-solid fa-cloud-arrow-up"></i> Save Purchase
                    </button>
                </div>
            </form>
        </div>
    </div>

    <script>
        (function () {
            const cratesInput = document.getElementById('crate_qty');
            const totalWeightInput = document.getElementById('total_weight');
            const weightCutInput = document.getElementById('weight_cut');
            const netWeightInput = document.getElementById('netweight');
            const rateInput = document.getElementById('rate');
            const totalAmountInput = document.getElementById('total_amount');
            const supplierSelect = document.getElementById('supplier_id');
            const regionHint = document.getElementById('regionHint');

            const CRATE_CUT_PER_UNIT = 0.5;   // kg cut per crate
            const PUNJAB_CUT_PERCENT = 0.02;  // 2% of total weight for Punjab suppliers

            function isPunjabSupplier() {
                const selectedOption = supplierSelect.options[supplierSelect.selectedIndex];
                const region = selectedOption ? (selectedOption.getAttribute('data-region') || '') : '';
                return region.trim().toLowerCase() === 'punjab';
            }

            function recalculate() {
                const crateQty = parseFloat(cratesInput.value) || 0;
                const totalWeight = parseFloat(totalWeightInput.value) || 0;
                const rate = parseFloat(rateInput.value) || 0;

                const crateCut = crateQty * CRATE_CUT_PER_UNIT;
                const punjab = isPunjabSupplier();
                const regionCut = punjab ? (totalWeight * PUNJAB_CUT_PERCENT) : 0;

                regionHint.classList.toggle('hidden', !punjab);

                let weightCut = crateCut + regionCut;
                let netWeight = totalWeight - weightCut;
                if (netWeight < 0) netWeight = 0;

                const totalAmount = netWeight * rate;

                weightCutInput.value = weightCut.toFixed(2);
                netWeightInput.value = netWeight.toFixed(2);
                totalAmountInput.value = totalAmount.toFixed(2);
            }

            [cratesInput, totalWeightInput, rateInput].forEach(el => {
                el.addEventListener('input', recalculate);
            });
            supplierSelect.addEventListener('change', recalculate);

            // Run once on load (handles edit mode / old() repopulation)
            recalculate();
        })();
    </script>
@endsection
